//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Wordsmith {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Wordsmith() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Wordsmith", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Page01DefaultItem01Home {
            get {
                return ResourceManager.GetString("Page01DefaultItem01Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Page01DefaultItem02Logout {
            get {
                return ResourceManager.GetString("Page01DefaultItem02Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Words.
        /// </summary>
        internal static string Page01DefaultItem03LoadWords {
            get {
                return ResourceManager.GetString("Page01DefaultItem03LoadWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Menu.
        /// </summary>
        internal static string Page01DefaultItem03WordMenu {
            get {
                return ResourceManager.GetString("Page01DefaultItem03WordMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Theme Menu.
        /// </summary>
        internal static string Page01DefaultItem03WordThemeMenu {
            get {
                return ResourceManager.GetString("Page01DefaultItem03WordThemeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Words.
        /// </summary>
        internal static string Page01DefaultItem04ViewWords {
            get {
                return ResourceManager.GetString("Page01DefaultItem04ViewWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Words.
        /// </summary>
        internal static string Page01DefaultItem05InputWords {
            get {
                return ResourceManager.GetString("Page01DefaultItem05InputWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Name: .
        /// </summary>
        internal static string Page01DefaultItem06LoginName {
            get {
                return ResourceManager.GetString("Page01DefaultItem06LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Page01DefaultItem07LoginButton {
            get {
                return ResourceManager.GetString("Page01DefaultItem07LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Password: .
        /// </summary>
        internal static string Page01DefaultItem07LoginPassword {
            get {
                return ResourceManager.GetString("Page01DefaultItem07LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Archive.
        /// </summary>
        internal static string Page01DefaultItem08GetArchive {
            get {
                return ResourceManager.GetString("Page01DefaultItem08GetArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Page02ViewWords01Search {
            get {
                return ResourceManager.GetString("Page02ViewWords01Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Words.
        /// </summary>
        internal static string Page03LoadWords01LoadWords {
            get {
                return ResourceManager.GetString("Page03LoadWords01LoadWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Input.
        /// </summary>
        internal static string Page04InputWords01WordInputWord {
            get {
                return ResourceManager.GetString("Page04InputWords01WordInputWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Theme Name.
        /// </summary>
        internal static string Page04InputWords02WordInputWordThemeName {
            get {
                return ResourceManager.GetString("Page04InputWords02WordInputWordThemeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pronounciation.
        /// </summary>
        internal static string Page04InputWords03WordInputPronounciation {
            get {
                return ResourceManager.GetString("Page04InputWords03WordInputPronounciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meaning.
        /// </summary>
        internal static string Page04InputWords04WordInputMeaning {
            get {
                return ResourceManager.GetString("Page04InputWords04WordInputMeaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etymology.
        /// </summary>
        internal static string Page04InputWords05WordInputEtymology {
            get {
                return ResourceManager.GetString("Page04InputWords05WordInputEtymology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        internal static string Page04InputWords06WordInputUsage {
            get {
                return ResourceManager.GetString("Page04InputWords06WordInputUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thought A Day.
        /// </summary>
        internal static string Page04InputWords07WordInputThoughtADay {
            get {
                return ResourceManager.GetString("Page04InputWords07WordInputThoughtADay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Page04InputWords08WordInputNotes {
            get {
                return ResourceManager.GetString("Page04InputWords08WordInputNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Page04InputWords09WordCreate {
            get {
                return ResourceManager.GetString("Page04InputWords09WordCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word edit.
        /// </summary>
        internal static string Page05EditWords01WordEditWord {
            get {
                return ResourceManager.GetString("Page05EditWords01WordEditWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Theme Name.
        /// </summary>
        internal static string Page05EditWords02WordEditWordThemeName {
            get {
                return ResourceManager.GetString("Page05EditWords02WordEditWordThemeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pronounciation.
        /// </summary>
        internal static string Page05EditWords03WordEditPronounciation {
            get {
                return ResourceManager.GetString("Page05EditWords03WordEditPronounciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meaning.
        /// </summary>
        internal static string Page05EditWords04WordEditMeaning {
            get {
                return ResourceManager.GetString("Page05EditWords04WordEditMeaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etymology.
        /// </summary>
        internal static string Page05EditWords05WordEditEtymology {
            get {
                return ResourceManager.GetString("Page05EditWords05WordEditEtymology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        internal static string Page05EditWords06WordEditUsage {
            get {
                return ResourceManager.GetString("Page05EditWords06WordEditUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thought A Day.
        /// </summary>
        internal static string Page05EditWords07WordEditThoughtADay {
            get {
                return ResourceManager.GetString("Page05EditWords07WordEditThoughtADay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Page05EditWords08WordEditNotes {
            get {
                return ResourceManager.GetString("Page05EditWords08WordEditNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Date:.
        /// </summary>
        internal static string Page05EditWords09WordInsert {
            get {
                return ResourceManager.GetString("Page05EditWords09WordInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Page05EditWords10WordUpdate {
            get {
                return ResourceManager.GetString("Page05EditWords10WordUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewed.
        /// </summary>
        internal static string Page05EditWords11WordReviewed {
            get {
                return ResourceManager.GetString("Page05EditWords11WordReviewed", resourceCulture);
            }
        }
    }
}
